---
- hosts: cluster
  become: yes
  
  vars:
    volume_name: data
    brick_dir: /home/ubuntu/gluster/data/brick0
    mount_dir: /mnt/data
    
  tasks:
    - import_tasks: "gluster-vol-{{ task }}.yml"

