---

- hosts: postgres
  become: yes
    
  tasks:
    - name: Deregister service in Consul
      ansible.builtin.uri:
        url: "http://localhost:8500/v1/agent/service/deregister/postgres-{{ (inventory_hostname.split('.')[0]) }}"
        method: PUT
      ignore_errors: yes
      tags:
        - deregister
  
    - name: Stop and disable Consul systemd service
      become_user: postgres
      become: yes
      ansible.builtin.systemd:
        name: container-postgres
        scope: user
        state: stopped
        enabled: no
    
    - name: Stop and remove Consul container
      become_user: postgres
      become: yes
      containers.podman.podman_container:
        name: postgres
        state: absent
        
    - name: Delete data directory and systemd unit file
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "/home/postgres/data/"
        - "/home/postgres/.config/systemd/user/container-postgres.service"

