---
- hosts: all
  become: yes
  
  vars:
    volume_name:
    brick_dir: /home/ubuntu/gluster/data/brick0
    mount_dir: /mnt/data

  tasks:
  - name: Unmount gluster volume and remove from fstab
    mount:
      path: "{{ mount_dir }}"
      state: absent
  
  - name: Stop gluster volume
    gluster_volume:
      name: data
      state: stopped
    run_once: true

  - name: Remove gluster volume
    gluster_volume:
      name: data
      state: absent
    run_once: true
      
  - name: Delete brick and mount directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
        - "{{ brick_dir }}"
        - "{{ mount_dir }}"

